project_id = "txuptwgqziperdffnuqq"

[functions.get-google-maps-key]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.send-message-notification]
verify_jwt = false

[functions.send-reminder-notification]
verify_jwt = false

[functions.create-rental-payment]
verify_jwt = true

[functions.verify-rental-payment]
verify_jwt = false

[functions.create-payment-authorization]
verify_jwt = true

[functions.capture-payment]
verify_jwt = true

[functions.verify-payment-authorization]
verify_jwt = false

[functions.manual-capture-payment]
verify_jwt = true

[functions.create-booking-from-checkout]
verify_jwt = false

[functions.update-listing-image]
verify_jwt = false

[functions.import-spacest-listings]
verify_jwt = true

[functions.update-postcodes]
verify_jwt = true

[functions.geocode-all-listings]
verify_jwt = true

[functions.geocode-addresses]
verify_jwt = true

[functions.import-spacest-listing-by-url]
verify_jwt = true

[functions.fix-spacest-listing-price]
verify_jwt = false