project_id = "txuptwgqziperdffnuqq"

[functions.get-google-maps-key]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.send-message-notification]
verify_jwt = false

[functions.send-reminder-notification]
verify_jwt = false

[functions.create-rental-payment]
verify_jwt = true

[functions.verify-rental-payment]
verify_jwt = false

[functions.create-payment-authorization]
verify_jwt = true

[functions.capture-payment]
verify_jwt = true

[functions.verify-payment-authorization]
verify_jwt = false

[functions.manual-capture-payment]
verify_jwt = true

[functions.create-booking-from-checkout]
verify_jwt = false